### ISSUE TITLE
Having Trouble Initializing the FCM Channel

### ISSUE THREAD

**Issue by SaniRiseUpLabs** [push-platform/fcm-channel-android#18]
I can't seem to get the host url right, can someone explain me where to find actual host, token and channel details to setup the fcm channel?

**Comment by joneserick** [comment]
As we managed to solve this by email I'm closing the issue. In order to maintain the solution available:

It was explained that the developer team must provide a local xml file containing the keys needed to the app work properly (host, **RapidPRO** user token and **RapidPRO** FCM channel id). After that, reference these strings on the code by accessing the resources.
